웹프/learnCSS/urls.py
from django.urls import path
from . import views

app_name = 'learnCSS'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('codeEditor/', views.codeEditor, name='codeEditor'),
    path('htmlanswer/create/<int:question_id>/', views.html_answer_create, name='html_answer_create'),
    path('htmlquestion/create/', views.html_create, name='html_create'),
    path('htmlquestion/modify/<int:question_id>/', views.html_question_modify, name='html_question_modify'),
    path('htmlquestion/delete/<int:question_id>/', views.html_question_delete, name='html_question_delete'),
    path('htmlanswer/modify/<int:answer_id>/', views.html_answer_modify, name='html_answer_modify'),
    path('htmlanswer/delete/<int:answer_id>/', views.html_answer_delete, name='html_answer_delete'),
]

웹프/test1/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp1 import views

app_name = 'apptest'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apptest/', include('testapp1.urls')),
    path('common/', include('common.urls')),
    path('learnCSS/', include('learnCSS.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

웹프/testapp1/urls.py
from django.urls import path
from . import views

app_name = 'apptest'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

웹프/learnCSS/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime  

# Create your models here.
class Html(models.Model):
    subject = models.CharField(max_length=200, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    css = models.TextField(null=True)
    html = models.TextField(null=True)
    content = models.TextField(null=True)
    # create_date = models.DateTimeField(auto_now_add=True)
    # modify_date = models.DateTimeField(null=True, blank=True)

    create_Date = models.DateTimeField(null=True)
    modify_Date = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return self.subject
        
class Html_Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    question = models.ForeignKey(Html, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    modify_Date = models.DateTimeField(null=True, blank=True)
    create_Date = models.DateTimeField()

웹프/testapp1/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField(null=True)
    
    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    content = models.TextField(null=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    create_date = models.DateTimeField(null=True)

웹프/learnCSS/forms.py
from django import forms
from learnCSS.models import Html,Html_Answer


class HtmlForm(forms.ModelForm):
    class Meta:
        model = Html # 사용할 모델
        fields = ['subject', 'html','css','content']
        labels = {
            'subject': '제목',
            'html': 'html',
            'css':'css',
            'content':'내용',
        }  
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Html_Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

웹프/learnCSS/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.utils import timezone
from .models import Html, Html_Answer
from .forms import HtmlForm, AnswerForm
from django.core.paginator import Paginator  
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
    """
    pybo 목록출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    html_list = Html.objects.order_by('-create_Date')

    # 페이징처리
    paginator = Paginator(html_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'html_list': page_obj}
    return render(request, 'learnCSS/index.html', context)

def codeEditor(request):
    return render(request, 'learnCSS/codeEditor.html')

# Create your views here.
def html_create(request):
    if request.method == 'POST':
        form = HtmlForm(request.POST)
        if form.is_valid():
            html = form.save(commit=False)
            html.author = request.user  # author 속성에 로그인 계정 저장
            html.create_Date = timezone.now()
            html.save()
            return redirect('learnCSS:index')
    else:
        form = HtmlForm()
    context = {'form': form}
    return render(request, 'learnCSS/html_create.html', context)

def detail(request, question_id):
    question = Html.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'learnCSS/learnCSS_detail.html', context)

@login_required(login_url='common:login')
def html_answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Html, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_Date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('learnCSS:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'learnCSS/learnCSS_detail.html', context)  

@login_required(login_url='common:login')
def html_question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = HtmlForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_Date = timezone.now()
            question.save()
            return redirect('learnCSS:index')
    else:
        form = HtmlForm()
    context = {'form': form}
    return render(request, 'learnCSS/html_create.html', context)


@login_required(login_url='common:login')
def html_question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Html, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('learnCSS:detail', question_id=question.id)

    if request.method == "POST":
        form = HtmlForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_Date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('learnCSS:detail', question_id=question.id)
    else:
        form = HtmlForm(instance=question)
    context = {'form': form}
    return render(request, 'learnCSS/html_create.html', context)

@login_required(login_url='common:login')
def html_question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Html, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('learnCSS:detail', question_id=question.id)
    question.delete()
    return redirect('learnCSS:index')

@login_required(login_url='common:login')
def html_answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Html_Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('learnCSS:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_Date = timezone.now()
            answer.save()
            return redirect('learnCSS:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'learnCSS/answer_form.html', context)

@login_required(login_url='common:login')
def html_answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Html_Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('learnCSS:detail', question_id=answer.question.id)

웹프/templates/learnCSS/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" 
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

웹프/templates/learnCSS/html_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
        <style class="outputstyle"> </style>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <div style="display: flex;">
        <div id="html" style="flex:1; height: 50vh; width: 45vw; display:inline-block;"></div>
        <div id="css" style="flex:1; margin-left: 5vh; height: 50vh; width: 45vw; display:inline-block;"></div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.16.2/min/vs/loader.js"></script>
    <div style="display: flex; flex-direction: column; align-items: center;">
        <div>
            <script>
                var html;
                require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.16.2/min/vs' }});
                require(['vs/editor/editor.main'], function() {
                    html = monaco.editor.create(document.getElementById('html'), {
                    theme: 'vs-dark',
                    fontFamily: 'Nanum Gothic Coding',
                    automaticLayout: true,
                    language: 'html',
                    value: [
                        '<!-- html -->',
                        '<!-- Please use class or id. -->',
                        '<!-- do not use class name "output" -->',
                        '<div class="main">',
                        '   ',
                        '</div>'
                    ].join('\n'),
                    });
                });
                var css;
                require.config({ paths: { 'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.16.2/min/vs' }});
                require(['vs/editor/editor.main'], function() {
                    css = monaco.editor.create(document.getElementById('css'), {
                    theme: 'vs-dark',
                    fontFamily: 'Nanum Gothic Coding',
                    automaticLayout: true,
                    language: 'css',
                    value: [
                    '/* css */',
                    '*,',
                    '*::after,',
                    '*::before {',
                    '    margin: 0;',
                    '    padding: 0;',
                    '    box-sizing: border-box;',
                    '}',
                    '.main{',
                    '   display: flex;',
                    '   justify-content: center;',
                    '   align-items: center;',
                    '   height: 100%;',
                    '}',
                    ''
                    ].join('\n'),
                    });
                });
                const run = () => {
                    const CSSValue = css.getValue();
                    const HTMLValue = html.getValue();
                    const output = document.getElementsByClassName("output")[0];
                    const outputstyle = document.getElementsByClassName("outputstyle")[0];
                    output.innerHTML = HTMLValue;
                    outputstyle.innerHTML = CSSValue;
                    const html_content = document.getElementsByClassName("html_content")[0];
                    const css_content = document.getElementsByClassName("css_content")[0];
                    html_content.innerHTML = `<label for="html">HTML</label><textarea class="form-control" name="html" id="html_content" rows="10">${HTMLValue}</textarea>`
                    css_content.innerHTML = `<label for="css">CSS</label><textarea class="form-control" name="css" id="html_content" rows="10">${CSSValue}</textarea>`
                    
                    }
            </script>
        </div>
        <div>
            <input type="button" onclick="run()" value="RUN" style="width: 5vh; height: 3vh; margin: 1.5vh 0;">
        </div>
        <div style="width: 50vw; height: 30vh; border: 1px solid gray; background-color: gray;">
            <div class="output" style="height: 100%;">
            
            </div>
        </div>
    </div>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
                <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group html_content" ><label for="html">HTML</label><textarea name="html" class="form-control" id="html" rows="10" >{{ form.html.value|default_if_none:'' }}</textarea></div>
        <div class="form-group css_content"><label for="css">CSS</label><textarea class="form-control" name="css" id="css" rows="10">{{ form.css.value|default_if_none:'' }}</textarea></div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}
</body>
</html>

웹프/templates/learnCSS/index.html
{% extends 'base.html' %}
{% load apptest_filter %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

</head>
<body>    
    <div class="body_div">
        <div class="title_div">
            <h1>Learn CSS</h1>
        </div>
        <br>
        <div class="content_div">
            <div class="container my-3">
                <table class="table">
                    <thead>
                    <tr class="text-center thead-dark">
                        <th>번호</th>
                        <th style="width:50%">제목</th>
                        <th>글쓴이</th>
                        <th>작성일시</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if html_list %}
                    {% for question in html_list %}
                    <tr class="text-center">
                        <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ html_list.paginator.count|sub:html_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td class="text-left">
                            <a href="{% url 'learnCSS:detail' question.id %}">{{ question.subject }}</a>
                            {% if question.html_answer_set.count > 0 %}
                                <span class="text-danger small ml-2">{{ question.html_answer_set.count }}</span>
                            {% endif %}
                        </td>
                        <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                        <td>{{ question.create_Date }}</td> 
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="3">질문이 없습니다.</td>
                    </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if html_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ html_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in html_list.paginator.page_range %}
            {% if page_number >= html_list.number|add:-5 and page_number <= html_list.number|add:5 %}
                {% if page_number == html_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if html_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ html_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        <a href="{% url 'learnCSS:html_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
    </div>    
</body>
</html>
{% endblock %}

웹프/templates/learnCSS/learnCSS_detail.html
   
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script>
    onload = () => {
        const CSSValue = document.getElementById("cssCode").innerHTML;
        const HTMLValue = document.getElementById("htmlCode").innerHTML;
        const output = document.getElementsByClassName("output")[0];
        const outputstyle = document.getElementsByClassName("outputstyle")[0];
        const outputdata = eval("convert(HTMLValue)");
        output.innerHTML = outputdata;
        outputstyle.innerHTML = CSSValue;
    }
    const convert = (data) => {
        if(data !== undefined && data !== null && data !== ''){
            data = String(data);

            data = data.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi, '');
            data = data.replace(/<\?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi, '');
            var element = document.createElement('div');
            element.innerHTML = data;
            data = element.textContent;
            element.textContent = '';
        }
        console.log(data);
        return data;
    }
</script>
<style class="outputstyle"></style>
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <div class="title_div">
    <h2>{{ question.subject }}</h2>
    </div>
<div class="container my-3">
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">        
        {% if question.modify_Date %}
        <div class="badge badge-light p-2 text-left mx-3">
            <div class="mb-2">modified at</div>
            <div>{{ question.modify_Date }}</div>
        </div>
        {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_Date }}</div>
                </div>
            </div>
                    {% if request.user == question.author %}
        <div class="my-3">
            <a href="{% url 'learnCSS:html_question_modify' question.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
    <a href="#" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'learnCSS:html_question_delete' question.id  %}">삭제</a>
        </div>
        {% endif %}
        </div>
    </div>
    <div class="card my-3" style="padding: 3vh; background-color: black; color: #ccc;">
        <div class="card-text" id="htmlCode" style="white-space: pre-line;">{{ question.html }}</div>
    </div>
    <div class="card my-3" style="padding: 3vh; background-color: black; color: #ccc;">
        <div class="card-text" id="cssCode" style="white-space: pre-line;">{{ question.css }}</div>
    </div>
    <div class="card my-3" style="background-color: #ccc;">
        <div class="card-body output" style="height: 100%;">

        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.html_answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.html_answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_Date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ answer.modify_Date }}</div>
            </div>
            {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_Date }}</div>
                </div>
            </div>        
            {% if request.user == answer.author %}
        <div class="my-3">
            <a href="{% url 'learnCSS:html_answer_modify' answer.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary " 
               data-uri="{% url 'learnCSS:html_answer_delete' answer.id  %}">삭제</a>
        </div>
        {% endif %}
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'learnCSS:html_answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

웹프/templates/learnCSS/learnCss_detil.html
   
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <div class="title_div">
    <h2>{{ question.subject }}</h2>
    </div>
<div class="container my-3">

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">        
                {% if question.modify_date %}
        <div class="badge badge-light p-2 text-left mx-3">
            <div class="mb-2">modified at</div>
            <div>{{ question.modify_date }}</div>
        </div>
        {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
                    {% if request.user == question.author %}
        <div class="my-3">
            <a href="{% url 'apptest:question_modify' question.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
    <a href="#" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'apptest:question_delete' question.id  %}">삭제</a>
        </div>
        {% endif %}
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ answer.modify_date }}</div>
            </div>
            {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>        
            {% if request.user == answer.author %}
        <div class="my-3">
            <a href="{% url 'apptest:answer_modify' answer.id  %}" 
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary " 
               data-uri="{% url 'apptest:answer_delete' answer.id  %}">삭제</a>
        </div>
        {% endif %}
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'apptest:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}