웹프/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

웹프/learnCSS/urls.py
from django.urls import path
from . import views

app_name = 'learnCSS'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('codeEditor/', views.codeEditor, name='codeEditor'),
    path('htmlanswer/create/<int:question_id>/', views.html_answer_create, name='html_answer_create'),
    path('htmlquestion/create/', views.html_create, name='html_create'),
    path('htmlquestion/modify/<int:question_id>/', views.html_question_modify, name='html_question_modify'),
    path('htmlquestion/delete/<int:question_id>/', views.html_question_delete, name='html_question_delete'),
    path('htmlanswer/modify/<int:answer_id>/', views.html_answer_modify, name='html_answer_modify'),
    path('htmlanswer/delete/<int:answer_id>/', views.html_answer_delete, name='html_answer_delete'),
]

웹프/test1/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp1 import views

app_name = 'apptest'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apptest/', include('testapp1.urls')),
    path('common/', include('common.urls')),
    path('learnCSS/', include('learnCSS.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

웹프/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="basebody">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
                  {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Logout)</a>
    {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">Login</a>
    {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apptest:index' %}">Community</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'learnCSS:index' %}">LearnCSS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
    </body>
</html>

웹프/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}